### ISSUE TITLE
Enhance defaulting of `spec.dataSinkRef`

### ISSUE THREAD

**Issue by maximiliantech** [openmcp-project/metrics-operator#30]
## Description
With #27 @mirzakopic introduced the configurability of a data sink (e.g. Dynatrace) via the `DataSink` CRD that serves kind of like Crossplane's `ProviderConfig`.

The deployed `DataSink` CR can be referenced via the `spec.dataSinkRef` field in the respective metric CRDs of the `api/v1alpha1/` package. This field is always an optional field, see

https://github.com/openmcp-project/metrics-operator/blob/2ee94331be9653e6b4122cb00de11c4f03726898/api/v1alpha1/metric_types.go#L65-L69

The controller already resolves the defaulting behaviour of `dataSinkRef` automatically in code, see
https://github.com/openmcp-project/metrics-operator/blob/bba110997df9a8a62c35b3ebc4e4facc8f635f34/internal/controller/datasink_utils.go#L68-L72

## Problem
For me as an end user who just uses the API/CRDs, I don't see this defaulting behaviour right from the beginning. It would be nice to **see the defaulting mechanism also reflected in the applied CR**.

### Example
After applying the following resource via `kubectl apply -f ...`
```yaml
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-total-pods
spec:
  name: pods-metric-total
  description: Pods
  target:
    kind: pod
    group: ""
    version: v1
  interval: 1m
```

the kube apiserver should default `spec.dataSinkRef` automatically like so:

```yaml
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-total-pods
spec:
  name: pods-metric-total
  description: Pods
  target:
    kind: pod
    group: ""
    version: v1
  interval: 1m
  dataSinkRef:
    name: default # spec.dataSinkRef gets automatically defaulted
```

## Proposal
Using Kubebuilders [CRD Validation](https://book.kubebuilder.io/reference/markers/crd-validation) mechanism to automatically default `spec.dataSinkRef` while applying one of the metric CRs at a K8s cluster.
