### ISSUE TITLE
ManagedMetric Not Filtering by kind/group/version

### ISSUE THREAD

**Issue by rouzbehsedighi** [openmcp-project/metrics-operator#47]
The ManagedMetric resource does not respect the spec's kind, group, or version fields. It appears to collect metrics from all Crossplane-managed resources, regardless of the specified fields.

Expected Behavior:

Given the following ManagedMetric:

```
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: ManagedMetric
metadata:
  name: managed-metric-subaccount
  namespace: metrics-operator
spec:
  name: managed-metric-subaccount
  description: Status metric created by an Operator
  kind: Subaccount
  group: account.btp.sap.crossplane.io
  version: v1alpha1
  interval: "1m"
```
It should only collect metrics from resources of:

apiVersion: account.btp.sap.crossplane.io
kind: Subaccount

Actual Behavior:

The ManagedMetric is collecting metrics from all managed resources, including unrelated kinds like Azure PostgreSQL.

Additionally, all the retrieved metrics are reported as if the resource kind is Subaccount, even when the actual resource is, for example,  Azure Keyvault.

![Image](https://github.com/user-attachments/assets/112e9820-5785-461f-afde-27b0ce8af670)

**Comment by maximiliantech** [comment]
I have synced about this bug with @mirzakopic and it seems that we have multiple bugs here at the same time: 

## Background to `ManagedMetric` API
The `ManagedMetric` API is important to cover the specific parts that are unique to the Crossplane framework of handling resources. For example: The `ManagedMetric` will **always** add the dimensions `Synced` and `Ready` and sends this to the data sink. These status conditions are unique for resources that come from any Crossplane provider. You will not see these fields in standard Kubernetes resources. 

Therefore, @mirzakopic introduced the `ManagedMetric` resource kind as way to define an "extension" for more specific metrics in the Kubernetes ecosystem instead of blowing up the standard `Metric` resource `spec`.

## Bugs that are occurring in this issue

### 1. Resource kind gets overwritten
As @rdksap pointed out in https://github.com/openmcp-project/metrics-operator/issues/47#issuecomment-3052620422, we need to fix these lines in order to not overwrite the name of a resource kind in every `ManagedResource` we collect.

But additionally, this leads to...

### 2. Bug in filtering resources
There seems to be a bug in the filtering. The GVK in the `ManagedMetric.spec` is meant to be used to filter resources in each of the dimensions. Let's have a look at the actually expected output for the given `ManagedMetric` configuration.

#### Input
```yaml
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: ManagedMetric
metadata:
  name: managed-metric-subaccount
  namespace: metrics-operator
spec:
  name: managed-metric-subaccount
  description: Status metric created by an Operator
  kind: Subaccount
  group: account.btp.sap.crossplane.io
  version: v1alpha1
  interval: "1m"
```

#### Expected Output
The output should be the number of resources in exactly this group, version, kind.

<table>
<tr>
 <td> apiVersion
 <td> kind
 <td> count
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Subaccount
 <td> 1
</table>

#### Input
```yaml
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: ManagedMetric
metadata:
  name: managed-metric-subaccount
  namespace: metrics-operator
spec:
  name: managed-metric-subaccount
  description: Status metric created by an Operator
  # no kind configured
  group: account.btp.sap.crossplane.io
  version: v1alpha1
  interval: "1m"
```

#### Expected Output
All Managed Resources in group `account.btp.sap.crossplane.io` and version `v1alpha1`.

<table>
<tr>
 <td> apiVersion
 <td> kind
 <td> count
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Subaccount
 <td> 1
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Entitlement
 <td> 4
</table>

#### Input
```yaml
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: ManagedMetric
metadata:
  name: managed-metric-subaccount
  namespace: metrics-operator
spec:
  name: managed-metric-subaccount
  description: Status metric created by an Operator
  # no kind configured
  # no group configured
  version: v1alpha1
  interval: "1m"
```

#### Expected Output
All Managed Resources in version `v1alpha1`, e.g. resources from BTP provider and Kubernetes provider.

<table>
<tr>
 <td> apiVersion
 <td> kind
 <td> count
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Subaccount
 <td> 1
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Entitlement
 <td> 4
<tr>
 <td> kubernetes.m.crossplane.io/v1alpha1
 <td> Object
 <td> 2
</table>

#### Input
```yaml
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: ManagedMetric
metadata:
  name: managed-metric-subaccount
  namespace: metrics-operator
spec:
  name: managed-metric-subaccount
  description: Status metric created by an Operator
  # no kind configured
  # no group configured
  # no version configured
  interval: "1m"
```

#### Expected Output
All Managed Resources in any group, any version and any kind. 

<table>
<tr>
 <td> apiVersion
 <td> kind
 <td> count
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Subaccount
 <td> 1
<tr>
 <td> account.btp.sap.crossplane.io/v1alpha1
 <td> Entitlement
 <td> 4
<tr>
 <td> kubernetes.m.crossplane.io/v1alpha1
 <td> Object
 <td> 2
<tr>
 <td> s3.aws.m.upbound.io/v1beta1
 <td> Bucket
 <td> 11
</table>

➡️ This can go on for more combinations of GVK configuration in the `ManagedMetric` resource.
